project:
  type: website
  output-dir: docs

website:
  title: "Statistical Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Deneme.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



